package pl.edu.pw.mini.hermant.gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.util.Objects;

public class AnalyzerChooserForm implements Form {

    private JComboBox<String> cbType;
    private JButton btnOk;
    private JPanel mainPane;

    public AnalyzerChooserForm() {
        btnOk.addActionListener(e -> {
            WindowBuilder builder = new WindowBuilder();
            Form form = Objects.equals(cbType.getSelectedItem(), "frequency") ?
                    new FrequencyAnalyzerForm() : new TimeAnalyzerForm();
            builder.setContentPane(form.getMainPanel()).
                    setMenuBar(form.getMenuBar()).
                    setSize(1920, 1080).
                    setPreferredSize(1920, 1080).
                    setMaximumSize(1920, 1080).
                    buildFrame();
            SwingUtilities.getWindowAncestor(mainPane).dispose();
        });
    }

    public JPanel getMainPanel() {
        return mainPane;
    }

    @Override
    public JMenuBar getMenuBar() {
        return null;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPane = new JPanel();
        mainPane.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("Select analysis type");
        mainPane.add(label1, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cbType = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("time");
        defaultComboBoxModel1.addElement("frequency");
        cbType.setModel(defaultComboBoxModel1);
        mainPane.add(cbType, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        btnOk = new JButton();
        btnOk.setText("ok");
        mainPane.add(btnOk, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPane;
    }

}
